/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/luistesperanca/osb-checker/go"
)

func main() {
	log.Printf("Server started")

	CatalogApiService := openapi.NewCatalogApiService()
	CatalogApiController := openapi.NewCatalogApiController(CatalogApiService)

	ServiceBindingsApiService := openapi.NewServiceBindingsApiService()
	ServiceBindingsApiController := openapi.NewServiceBindingsApiController(ServiceBindingsApiService)

	ServiceInstancesApiService := openapi.NewServiceInstancesApiService()
	ServiceInstancesApiController := openapi.NewServiceInstancesApiController(ServiceInstancesApiService)

	router := openapi.NewRouter(CatalogApiController, ServiceBindingsApiController, ServiceInstancesApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
