/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ServiceInstanceProvisionRequest struct for ServiceInstanceProvisionRequest
type ServiceInstanceProvisionRequest struct {
	ServiceId string `json:"service_id"`
	PlanId string `json:"plan_id"`
	// See [Context Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object) for more details.
	Context *map[string]interface{} `json:"context,omitempty"`
	OrganizationGuid string `json:"organization_guid"`
	SpaceGuid string `json:"space_guid"`
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
	MaintenanceInfo *MaintenanceInfo `json:"maintenance_info,omitempty"`
}

// NewServiceInstanceProvisionRequest instantiates a new ServiceInstanceProvisionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceInstanceProvisionRequest(serviceId string, planId string, organizationGuid string, spaceGuid string) *ServiceInstanceProvisionRequest {
	this := ServiceInstanceProvisionRequest{}
	this.ServiceId = serviceId
	this.PlanId = planId
	this.OrganizationGuid = organizationGuid
	this.SpaceGuid = spaceGuid
	return &this
}

// NewServiceInstanceProvisionRequestWithDefaults instantiates a new ServiceInstanceProvisionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceInstanceProvisionRequestWithDefaults() *ServiceInstanceProvisionRequest {
	this := ServiceInstanceProvisionRequest{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *ServiceInstanceProvisionRequest) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *ServiceInstanceProvisionRequest) GetServiceIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *ServiceInstanceProvisionRequest) SetServiceId(v string) {
	o.ServiceId = v
}

// GetPlanId returns the PlanId field value
func (o *ServiceInstanceProvisionRequest) GetPlanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value
// and a boolean to check if the value has been set.
func (o *ServiceInstanceProvisionRequest) GetPlanIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PlanId, true
}

// SetPlanId sets field value
func (o *ServiceInstanceProvisionRequest) SetPlanId(v string) {
	o.PlanId = v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *ServiceInstanceProvisionRequest) GetContext() map[string]interface{} {
	if o == nil || o.Context == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceProvisionRequest) GetContextOk() (*map[string]interface{}, bool) {
	if o == nil || o.Context == nil {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *ServiceInstanceProvisionRequest) HasContext() bool {
	if o != nil && o.Context != nil {
		return true
	}

	return false
}

// SetContext gets a reference to the given map[string]interface{} and assigns it to the Context field.
func (o *ServiceInstanceProvisionRequest) SetContext(v map[string]interface{}) {
	o.Context = &v
}

// GetOrganizationGuid returns the OrganizationGuid field value
func (o *ServiceInstanceProvisionRequest) GetOrganizationGuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationGuid
}

// GetOrganizationGuidOk returns a tuple with the OrganizationGuid field value
// and a boolean to check if the value has been set.
func (o *ServiceInstanceProvisionRequest) GetOrganizationGuidOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.OrganizationGuid, true
}

// SetOrganizationGuid sets field value
func (o *ServiceInstanceProvisionRequest) SetOrganizationGuid(v string) {
	o.OrganizationGuid = v
}

// GetSpaceGuid returns the SpaceGuid field value
func (o *ServiceInstanceProvisionRequest) GetSpaceGuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SpaceGuid
}

// GetSpaceGuidOk returns a tuple with the SpaceGuid field value
// and a boolean to check if the value has been set.
func (o *ServiceInstanceProvisionRequest) GetSpaceGuidOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SpaceGuid, true
}

// SetSpaceGuid sets field value
func (o *ServiceInstanceProvisionRequest) SetSpaceGuid(v string) {
	o.SpaceGuid = v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *ServiceInstanceProvisionRequest) GetParameters() map[string]interface{} {
	if o == nil || o.Parameters == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceProvisionRequest) GetParametersOk() (*map[string]interface{}, bool) {
	if o == nil || o.Parameters == nil {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *ServiceInstanceProvisionRequest) HasParameters() bool {
	if o != nil && o.Parameters != nil {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]interface{} and assigns it to the Parameters field.
func (o *ServiceInstanceProvisionRequest) SetParameters(v map[string]interface{}) {
	o.Parameters = &v
}

// GetMaintenanceInfo returns the MaintenanceInfo field value if set, zero value otherwise.
func (o *ServiceInstanceProvisionRequest) GetMaintenanceInfo() MaintenanceInfo {
	if o == nil || o.MaintenanceInfo == nil {
		var ret MaintenanceInfo
		return ret
	}
	return *o.MaintenanceInfo
}

// GetMaintenanceInfoOk returns a tuple with the MaintenanceInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceProvisionRequest) GetMaintenanceInfoOk() (*MaintenanceInfo, bool) {
	if o == nil || o.MaintenanceInfo == nil {
		return nil, false
	}
	return o.MaintenanceInfo, true
}

// HasMaintenanceInfo returns a boolean if a field has been set.
func (o *ServiceInstanceProvisionRequest) HasMaintenanceInfo() bool {
	if o != nil && o.MaintenanceInfo != nil {
		return true
	}

	return false
}

// SetMaintenanceInfo gets a reference to the given MaintenanceInfo and assigns it to the MaintenanceInfo field.
func (o *ServiceInstanceProvisionRequest) SetMaintenanceInfo(v MaintenanceInfo) {
	o.MaintenanceInfo = &v
}

func (o ServiceInstanceProvisionRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["service_id"] = o.ServiceId
	}
	if true {
		toSerialize["plan_id"] = o.PlanId
	}
	if o.Context != nil {
		toSerialize["context"] = o.Context
	}
	if true {
		toSerialize["organization_guid"] = o.OrganizationGuid
	}
	if true {
		toSerialize["space_guid"] = o.SpaceGuid
	}
	if o.Parameters != nil {
		toSerialize["parameters"] = o.Parameters
	}
	if o.MaintenanceInfo != nil {
		toSerialize["maintenance_info"] = o.MaintenanceInfo
	}
	return json.Marshal(toSerialize)
}

type NullableServiceInstanceProvisionRequest struct {
	value *ServiceInstanceProvisionRequest
	isSet bool
}

func (v NullableServiceInstanceProvisionRequest) Get() *ServiceInstanceProvisionRequest {
	return v.value
}

func (v *NullableServiceInstanceProvisionRequest) Set(val *ServiceInstanceProvisionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceInstanceProvisionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceInstanceProvisionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceInstanceProvisionRequest(val *ServiceInstanceProvisionRequest) *NullableServiceInstanceProvisionRequest {
	return &NullableServiceInstanceProvisionRequest{value: val, isSet: true}
}

func (v NullableServiceInstanceProvisionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceInstanceProvisionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


