/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SchemasObject struct for SchemasObject
type SchemasObject struct {
	ServiceInstance *ServiceInstanceSchemaObject `json:"service_instance,omitempty"`
	ServiceBinding *ServiceBindingSchemaObject `json:"service_binding,omitempty"`
}

// NewSchemasObject instantiates a new SchemasObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemasObject() *SchemasObject {
	this := SchemasObject{}
	return &this
}

// NewSchemasObjectWithDefaults instantiates a new SchemasObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemasObjectWithDefaults() *SchemasObject {
	this := SchemasObject{}
	return &this
}

// GetServiceInstance returns the ServiceInstance field value if set, zero value otherwise.
func (o *SchemasObject) GetServiceInstance() ServiceInstanceSchemaObject {
	if o == nil || o.ServiceInstance == nil {
		var ret ServiceInstanceSchemaObject
		return ret
	}
	return *o.ServiceInstance
}

// GetServiceInstanceOk returns a tuple with the ServiceInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemasObject) GetServiceInstanceOk() (*ServiceInstanceSchemaObject, bool) {
	if o == nil || o.ServiceInstance == nil {
		return nil, false
	}
	return o.ServiceInstance, true
}

// HasServiceInstance returns a boolean if a field has been set.
func (o *SchemasObject) HasServiceInstance() bool {
	if o != nil && o.ServiceInstance != nil {
		return true
	}

	return false
}

// SetServiceInstance gets a reference to the given ServiceInstanceSchemaObject and assigns it to the ServiceInstance field.
func (o *SchemasObject) SetServiceInstance(v ServiceInstanceSchemaObject) {
	o.ServiceInstance = &v
}

// GetServiceBinding returns the ServiceBinding field value if set, zero value otherwise.
func (o *SchemasObject) GetServiceBinding() ServiceBindingSchemaObject {
	if o == nil || o.ServiceBinding == nil {
		var ret ServiceBindingSchemaObject
		return ret
	}
	return *o.ServiceBinding
}

// GetServiceBindingOk returns a tuple with the ServiceBinding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemasObject) GetServiceBindingOk() (*ServiceBindingSchemaObject, bool) {
	if o == nil || o.ServiceBinding == nil {
		return nil, false
	}
	return o.ServiceBinding, true
}

// HasServiceBinding returns a boolean if a field has been set.
func (o *SchemasObject) HasServiceBinding() bool {
	if o != nil && o.ServiceBinding != nil {
		return true
	}

	return false
}

// SetServiceBinding gets a reference to the given ServiceBindingSchemaObject and assigns it to the ServiceBinding field.
func (o *SchemasObject) SetServiceBinding(v ServiceBindingSchemaObject) {
	o.ServiceBinding = &v
}

func (o SchemasObject) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ServiceInstance != nil {
		toSerialize["service_instance"] = o.ServiceInstance
	}
	if o.ServiceBinding != nil {
		toSerialize["service_binding"] = o.ServiceBinding
	}
	return json.Marshal(toSerialize)
}

type NullableSchemasObject struct {
	value *SchemasObject
	isSet bool
}

func (v NullableSchemasObject) Get() *SchemasObject {
	return v.value
}

func (v *NullableSchemasObject) Set(val *SchemasObject) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemasObject) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemasObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemasObject(val *SchemasObject) *NullableSchemasObject {
	return &NullableSchemasObject{value: val, isSet: true}
}

func (v NullableSchemasObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemasObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


