/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ServiceInstanceUpdateRequest struct for ServiceInstanceUpdateRequest
type ServiceInstanceUpdateRequest struct {
	// See [Context Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object) for more details.
	Context *map[string]interface{} `json:"context,omitempty"`
	ServiceId string `json:"service_id"`
	PlanId *string `json:"plan_id,omitempty"`
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
	PreviousValues *ServiceInstancePreviousValues `json:"previous_values,omitempty"`
	MaintenanceInfo *MaintenanceInfo `json:"maintenance_info,omitempty"`
}

// NewServiceInstanceUpdateRequest instantiates a new ServiceInstanceUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceInstanceUpdateRequest(serviceId string) *ServiceInstanceUpdateRequest {
	this := ServiceInstanceUpdateRequest{}
	this.ServiceId = serviceId
	return &this
}

// NewServiceInstanceUpdateRequestWithDefaults instantiates a new ServiceInstanceUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceInstanceUpdateRequestWithDefaults() *ServiceInstanceUpdateRequest {
	this := ServiceInstanceUpdateRequest{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *ServiceInstanceUpdateRequest) GetContext() map[string]interface{} {
	if o == nil || o.Context == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceUpdateRequest) GetContextOk() (*map[string]interface{}, bool) {
	if o == nil || o.Context == nil {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *ServiceInstanceUpdateRequest) HasContext() bool {
	if o != nil && o.Context != nil {
		return true
	}

	return false
}

// SetContext gets a reference to the given map[string]interface{} and assigns it to the Context field.
func (o *ServiceInstanceUpdateRequest) SetContext(v map[string]interface{}) {
	o.Context = &v
}

// GetServiceId returns the ServiceId field value
func (o *ServiceInstanceUpdateRequest) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *ServiceInstanceUpdateRequest) GetServiceIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *ServiceInstanceUpdateRequest) SetServiceId(v string) {
	o.ServiceId = v
}

// GetPlanId returns the PlanId field value if set, zero value otherwise.
func (o *ServiceInstanceUpdateRequest) GetPlanId() string {
	if o == nil || o.PlanId == nil {
		var ret string
		return ret
	}
	return *o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceUpdateRequest) GetPlanIdOk() (*string, bool) {
	if o == nil || o.PlanId == nil {
		return nil, false
	}
	return o.PlanId, true
}

// HasPlanId returns a boolean if a field has been set.
func (o *ServiceInstanceUpdateRequest) HasPlanId() bool {
	if o != nil && o.PlanId != nil {
		return true
	}

	return false
}

// SetPlanId gets a reference to the given string and assigns it to the PlanId field.
func (o *ServiceInstanceUpdateRequest) SetPlanId(v string) {
	o.PlanId = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *ServiceInstanceUpdateRequest) GetParameters() map[string]interface{} {
	if o == nil || o.Parameters == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceUpdateRequest) GetParametersOk() (*map[string]interface{}, bool) {
	if o == nil || o.Parameters == nil {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *ServiceInstanceUpdateRequest) HasParameters() bool {
	if o != nil && o.Parameters != nil {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]interface{} and assigns it to the Parameters field.
func (o *ServiceInstanceUpdateRequest) SetParameters(v map[string]interface{}) {
	o.Parameters = &v
}

// GetPreviousValues returns the PreviousValues field value if set, zero value otherwise.
func (o *ServiceInstanceUpdateRequest) GetPreviousValues() ServiceInstancePreviousValues {
	if o == nil || o.PreviousValues == nil {
		var ret ServiceInstancePreviousValues
		return ret
	}
	return *o.PreviousValues
}

// GetPreviousValuesOk returns a tuple with the PreviousValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceUpdateRequest) GetPreviousValuesOk() (*ServiceInstancePreviousValues, bool) {
	if o == nil || o.PreviousValues == nil {
		return nil, false
	}
	return o.PreviousValues, true
}

// HasPreviousValues returns a boolean if a field has been set.
func (o *ServiceInstanceUpdateRequest) HasPreviousValues() bool {
	if o != nil && o.PreviousValues != nil {
		return true
	}

	return false
}

// SetPreviousValues gets a reference to the given ServiceInstancePreviousValues and assigns it to the PreviousValues field.
func (o *ServiceInstanceUpdateRequest) SetPreviousValues(v ServiceInstancePreviousValues) {
	o.PreviousValues = &v
}

// GetMaintenanceInfo returns the MaintenanceInfo field value if set, zero value otherwise.
func (o *ServiceInstanceUpdateRequest) GetMaintenanceInfo() MaintenanceInfo {
	if o == nil || o.MaintenanceInfo == nil {
		var ret MaintenanceInfo
		return ret
	}
	return *o.MaintenanceInfo
}

// GetMaintenanceInfoOk returns a tuple with the MaintenanceInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceUpdateRequest) GetMaintenanceInfoOk() (*MaintenanceInfo, bool) {
	if o == nil || o.MaintenanceInfo == nil {
		return nil, false
	}
	return o.MaintenanceInfo, true
}

// HasMaintenanceInfo returns a boolean if a field has been set.
func (o *ServiceInstanceUpdateRequest) HasMaintenanceInfo() bool {
	if o != nil && o.MaintenanceInfo != nil {
		return true
	}

	return false
}

// SetMaintenanceInfo gets a reference to the given MaintenanceInfo and assigns it to the MaintenanceInfo field.
func (o *ServiceInstanceUpdateRequest) SetMaintenanceInfo(v MaintenanceInfo) {
	o.MaintenanceInfo = &v
}

func (o ServiceInstanceUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Context != nil {
		toSerialize["context"] = o.Context
	}
	if true {
		toSerialize["service_id"] = o.ServiceId
	}
	if o.PlanId != nil {
		toSerialize["plan_id"] = o.PlanId
	}
	if o.Parameters != nil {
		toSerialize["parameters"] = o.Parameters
	}
	if o.PreviousValues != nil {
		toSerialize["previous_values"] = o.PreviousValues
	}
	if o.MaintenanceInfo != nil {
		toSerialize["maintenance_info"] = o.MaintenanceInfo
	}
	return json.Marshal(toSerialize)
}

type NullableServiceInstanceUpdateRequest struct {
	value *ServiceInstanceUpdateRequest
	isSet bool
}

func (v NullableServiceInstanceUpdateRequest) Get() *ServiceInstanceUpdateRequest {
	return v.value
}

func (v *NullableServiceInstanceUpdateRequest) Set(val *ServiceInstanceUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceInstanceUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceInstanceUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceInstanceUpdateRequest(val *ServiceInstanceUpdateRequest) *NullableServiceInstanceUpdateRequest {
	return &NullableServiceInstanceUpdateRequest{value: val, isSet: true}
}

func (v NullableServiceInstanceUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceInstanceUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


