/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ServiceBindingSchemaObject struct for ServiceBindingSchemaObject
type ServiceBindingSchemaObject struct {
	Create *SchemaParameters `json:"create,omitempty"`
}

// NewServiceBindingSchemaObject instantiates a new ServiceBindingSchemaObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceBindingSchemaObject() *ServiceBindingSchemaObject {
	this := ServiceBindingSchemaObject{}
	return &this
}

// NewServiceBindingSchemaObjectWithDefaults instantiates a new ServiceBindingSchemaObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceBindingSchemaObjectWithDefaults() *ServiceBindingSchemaObject {
	this := ServiceBindingSchemaObject{}
	return &this
}

// GetCreate returns the Create field value if set, zero value otherwise.
func (o *ServiceBindingSchemaObject) GetCreate() SchemaParameters {
	if o == nil || o.Create == nil {
		var ret SchemaParameters
		return ret
	}
	return *o.Create
}

// GetCreateOk returns a tuple with the Create field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceBindingSchemaObject) GetCreateOk() (*SchemaParameters, bool) {
	if o == nil || o.Create == nil {
		return nil, false
	}
	return o.Create, true
}

// HasCreate returns a boolean if a field has been set.
func (o *ServiceBindingSchemaObject) HasCreate() bool {
	if o != nil && o.Create != nil {
		return true
	}

	return false
}

// SetCreate gets a reference to the given SchemaParameters and assigns it to the Create field.
func (o *ServiceBindingSchemaObject) SetCreate(v SchemaParameters) {
	o.Create = &v
}

func (o ServiceBindingSchemaObject) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Create != nil {
		toSerialize["create"] = o.Create
	}
	return json.Marshal(toSerialize)
}

type NullableServiceBindingSchemaObject struct {
	value *ServiceBindingSchemaObject
	isSet bool
}

func (v NullableServiceBindingSchemaObject) Get() *ServiceBindingSchemaObject {
	return v.value
}

func (v *NullableServiceBindingSchemaObject) Set(val *ServiceBindingSchemaObject) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceBindingSchemaObject) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceBindingSchemaObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceBindingSchemaObject(val *ServiceBindingSchemaObject) *NullableServiceBindingSchemaObject {
	return &NullableServiceBindingSchemaObject{value: val, isSet: true}
}

func (v NullableServiceBindingSchemaObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceBindingSchemaObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


