/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// CatalogApiService is a service that implents the logic for the CatalogApiServicer
// This service should implement the business logic for every endpoint for the CatalogApi API. 
// Include any external packages or services that will be required by this service.
type CatalogApiService struct {
}

// NewCatalogApiService creates a default api service
func NewCatalogApiService() CatalogApiServicer {
	return &CatalogApiService{}
}

// CatalogGet - get the catalog of services that the service broker offers
func (s *CatalogApiService) CatalogGet(ctx context.Context, xBrokerAPIVersion string, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string) (ImplResponse, error) {
	// TODO - update CatalogGet with the required logic for this service method.
	// Add api_catalog_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Catalog{}) or use other options such as http.Ok ...
	//return Response(200, Catalog{}), nil

	//TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	//return Response(401, Error{}), nil

	//TODO: Uncomment the next line to return response Response(412, Error{}) or use other options such as http.Ok ...
	//return Response(412, Error{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CatalogGet method not implemented")
}

