/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// ServiceBindingsApiService is a service that implents the logic for the ServiceBindingsApiServicer
// This service should implement the business logic for every endpoint for the ServiceBindingsApi API. 
// Include any external packages or services that will be required by this service.
type ServiceBindingsApiService struct {
}

// NewServiceBindingsApiService creates a default api service
func NewServiceBindingsApiService() ServiceBindingsApiServicer {
	return &ServiceBindingsApiService{}
}

// ServiceBindingBinding - generation of a service binding
func (s *ServiceBindingsApiService) ServiceBindingBinding(ctx context.Context, xBrokerAPIVersion string, instanceId string, bindingId string, body ServiceBindingRequest, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, acceptsIncomplete bool) (ImplResponse, error) {
	// TODO - update ServiceBindingBinding with the required logic for this service method.
	// Add api_service_bindings_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ServiceBindingResponse{}) or use other options such as http.Ok ...
	//return Response(200, ServiceBindingResponse{}), nil

	//TODO: Uncomment the next line to return response Response(201, ServiceBindingResponse{}) or use other options such as http.Ok ...
	//return Response(201, ServiceBindingResponse{}), nil

	//TODO: Uncomment the next line to return response Response(202, AsyncOperation{}) or use other options such as http.Ok ...
	//return Response(202, AsyncOperation{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	//return Response(401, Error{}), nil

	//TODO: Uncomment the next line to return response Response(409, Error{}) or use other options such as http.Ok ...
	//return Response(409, Error{}), nil

	//TODO: Uncomment the next line to return response Response(410, Error{}) or use other options such as http.Ok ...
	//return Response(410, Error{}), nil

	//TODO: Uncomment the next line to return response Response(412, Error{}) or use other options such as http.Ok ...
	//return Response(412, Error{}), nil

	//TODO: Uncomment the next line to return response Response(422, Error{}) or use other options such as http.Ok ...
	//return Response(422, Error{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ServiceBindingBinding method not implemented")
}

// ServiceBindingGet - gets a service binding
func (s *ServiceBindingsApiService) ServiceBindingGet(ctx context.Context, xBrokerAPIVersion string, instanceId string, bindingId string, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, serviceId string, planId string) (ImplResponse, error) {
	// TODO - update ServiceBindingGet with the required logic for this service method.
	// Add api_service_bindings_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ServiceBindingResource{}) or use other options such as http.Ok ...
	//return Response(200, ServiceBindingResource{}), nil

	//TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	//return Response(401, Error{}), nil

	//TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	//return Response(404, Error{}), nil

	//TODO: Uncomment the next line to return response Response(412, Error{}) or use other options such as http.Ok ...
	//return Response(412, Error{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ServiceBindingGet method not implemented")
}

// ServiceBindingLastOperationGet - last requested operation state for service binding
func (s *ServiceBindingsApiService) ServiceBindingLastOperationGet(ctx context.Context, xBrokerAPIVersion string, instanceId string, bindingId string, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, serviceId string, planId string, operation string) (ImplResponse, error) {
	// TODO - update ServiceBindingLastOperationGet with the required logic for this service method.
	// Add api_service_bindings_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, LastOperationResource{}) or use other options such as http.Ok ...
	//return Response(200, LastOperationResource{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	//return Response(401, Error{}), nil

	//TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	//return Response(404, Error{}), nil

	//TODO: Uncomment the next line to return response Response(410, Error{}) or use other options such as http.Ok ...
	//return Response(410, Error{}), nil

	//TODO: Uncomment the next line to return response Response(412, Error{}) or use other options such as http.Ok ...
	//return Response(412, Error{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ServiceBindingLastOperationGet method not implemented")
}

// ServiceBindingUnbinding - deprovision of a service binding
func (s *ServiceBindingsApiService) ServiceBindingUnbinding(ctx context.Context, xBrokerAPIVersion string, instanceId string, bindingId string, serviceId string, planId string, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, acceptsIncomplete bool) (ImplResponse, error) {
	// TODO - update ServiceBindingUnbinding with the required logic for this service method.
	// Add api_service_bindings_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(200, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(202, AsyncOperation{}) or use other options such as http.Ok ...
	//return Response(202, AsyncOperation{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	//return Response(401, Error{}), nil

	//TODO: Uncomment the next line to return response Response(410, Error{}) or use other options such as http.Ok ...
	//return Response(410, Error{}), nil

	//TODO: Uncomment the next line to return response Response(412, Error{}) or use other options such as http.Ok ...
	//return Response(412, Error{}), nil

	//TODO: Uncomment the next line to return response Response(422, Error{}) or use other options such as http.Ok ...
	//return Response(422, Error{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ServiceBindingUnbinding method not implemented")
}

