/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// ServiceInstancesApiService is a service that implents the logic for the ServiceInstancesApiServicer
// This service should implement the business logic for every endpoint for the ServiceInstancesApi API. 
// Include any external packages or services that will be required by this service.
type ServiceInstancesApiService struct {
}

// NewServiceInstancesApiService creates a default api service
func NewServiceInstancesApiService() ServiceInstancesApiServicer {
	return &ServiceInstancesApiService{}
}

// ServiceInstanceDeprovision - deprovision a service instance
func (s *ServiceInstancesApiService) ServiceInstanceDeprovision(ctx context.Context, xBrokerAPIVersion string, instanceId string, serviceId string, planId string, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, acceptsIncomplete bool) (ImplResponse, error) {
	// TODO - update ServiceInstanceDeprovision with the required logic for this service method.
	// Add api_service_instances_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(200, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(202, AsyncOperation{}) or use other options such as http.Ok ...
	//return Response(202, AsyncOperation{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	//return Response(401, Error{}), nil

	//TODO: Uncomment the next line to return response Response(410, Error{}) or use other options such as http.Ok ...
	//return Response(410, Error{}), nil

	//TODO: Uncomment the next line to return response Response(412, Error{}) or use other options such as http.Ok ...
	//return Response(412, Error{}), nil

	//TODO: Uncomment the next line to return response Response(422, Error{}) or use other options such as http.Ok ...
	//return Response(422, Error{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ServiceInstanceDeprovision method not implemented")
}

// ServiceInstanceGet - gets a service instance
func (s *ServiceInstancesApiService) ServiceInstanceGet(ctx context.Context, xBrokerAPIVersion string, instanceId string, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, serviceId string, planId string) (ImplResponse, error) {
	// TODO - update ServiceInstanceGet with the required logic for this service method.
	// Add api_service_instances_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ServiceInstanceResource{}) or use other options such as http.Ok ...
	//return Response(200, ServiceInstanceResource{}), nil

	//TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	//return Response(401, Error{}), nil

	//TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	//return Response(404, Error{}), nil

	//TODO: Uncomment the next line to return response Response(412, Error{}) or use other options such as http.Ok ...
	//return Response(412, Error{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ServiceInstanceGet method not implemented")
}

// ServiceInstanceLastOperationGet - last requested operation state for service instance
func (s *ServiceInstancesApiService) ServiceInstanceLastOperationGet(ctx context.Context, xBrokerAPIVersion string, instanceId string, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, serviceId string, planId string, operation string) (ImplResponse, error) {
	// TODO - update ServiceInstanceLastOperationGet with the required logic for this service method.
	// Add api_service_instances_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, LastOperationResource{}) or use other options such as http.Ok ...
	//return Response(200, LastOperationResource{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	//return Response(401, Error{}), nil

	//TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	//return Response(404, Error{}), nil

	//TODO: Uncomment the next line to return response Response(410, Error{}) or use other options such as http.Ok ...
	//return Response(410, Error{}), nil

	//TODO: Uncomment the next line to return response Response(412, Error{}) or use other options such as http.Ok ...
	//return Response(412, Error{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ServiceInstanceLastOperationGet method not implemented")
}

// ServiceInstanceProvision - provision a service instance
func (s *ServiceInstancesApiService) ServiceInstanceProvision(ctx context.Context, xBrokerAPIVersion string, instanceId string, body ServiceInstanceProvisionRequest, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, acceptsIncomplete bool) (ImplResponse, error) {
	// TODO - update ServiceInstanceProvision with the required logic for this service method.
	// Add api_service_instances_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ServiceInstanceProvisionResponse{}) or use other options such as http.Ok ...
	//return Response(200, ServiceInstanceProvisionResponse{}), nil

	//TODO: Uncomment the next line to return response Response(201, ServiceInstanceProvisionResponse{}) or use other options such as http.Ok ...
	//return Response(201, ServiceInstanceProvisionResponse{}), nil

	//TODO: Uncomment the next line to return response Response(202, ServiceInstanceAsyncOperation{}) or use other options such as http.Ok ...
	//return Response(202, ServiceInstanceAsyncOperation{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	//return Response(401, Error{}), nil

	//TODO: Uncomment the next line to return response Response(409, Error{}) or use other options such as http.Ok ...
	//return Response(409, Error{}), nil

	//TODO: Uncomment the next line to return response Response(412, Error{}) or use other options such as http.Ok ...
	//return Response(412, Error{}), nil

	//TODO: Uncomment the next line to return response Response(422, Error{}) or use other options such as http.Ok ...
	//return Response(422, Error{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ServiceInstanceProvision method not implemented")
}

// ServiceInstanceUpdate - update a service instance
func (s *ServiceInstancesApiService) ServiceInstanceUpdate(ctx context.Context, xBrokerAPIVersion string, instanceId string, body ServiceInstanceUpdateRequest, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, acceptsIncomplete bool) (ImplResponse, error) {
	// TODO - update ServiceInstanceUpdate with the required logic for this service method.
	// Add api_service_instances_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(200, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(202, ServiceInstanceAsyncOperation{}) or use other options such as http.Ok ...
	//return Response(202, ServiceInstanceAsyncOperation{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	//return Response(401, Error{}), nil

	//TODO: Uncomment the next line to return response Response(412, Error{}) or use other options such as http.Ok ...
	//return Response(412, Error{}), nil

	//TODO: Uncomment the next line to return response Response(422, Error{}) or use other options such as http.Ok ...
	//return Response(422, Error{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ServiceInstanceUpdate method not implemented")
}

