name: CI

on: [ push, pull_request ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.1
      - name: tag
        run: |
          echo "version " + $VERSION
          git tag $VERSION
          git push origin $VERSION
        env:
          VERSION: ${{ env.GITHUB_RUN_ID }}
      - name: publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull
          ./create-release.sh
